// Auto-generated by build.ts - do not edit
// This placeholder is used in dev mode; the real file is generated at build time
export type WebAsset = { mime: string; data: string; binary?: boolean }
export const webAssets: Record<string, WebAsset> = {}
